version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: stopheus
      POSTGRES_PASSWORD: stopheus_password
      POSTGRES_DB: stopheus_db
    volumes:
      - db-data:/var/lib/postgresql/data
      # Mount the init SQL so Postgres runs it on first initialization
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - stopheus-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      # Compose will merge env_file and these; override/add as needed
      POSTGRES_URL: "postgres://stopheus:stopheus_password@db:5432/stopheus_db"
    ports:
      - "48492:48492"
    restart: unless-stopped
    networks:
      - stopheus-net
    command: ["bun", "prod"]

volumes:
  db-data:

networks:
  stopheus-net:
    driver: bridge
