CREATE TABLE IF NOT EXISTS requests (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,
  ts TEXT NOT NULL,
  backend_ts TEXT NOT NULL UNIQUE,
  resolved BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (channel, ts)
);
